version: '3.7'

volumes:
  node_modules:

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
    command: 'npm run serve'
    environment:
      - NODE_ENV=dev
<% if (hasNightwatch) { _%>

  test:
    build:
      context: .
      target: dev
    # Add script to wait for app and selinium
    command: 'sh -c "sleep 5 && pm run test:e2e"'
    environment:
      - 'LAUNCH_URL=http://app:8080'
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    volumes:
      - ./:/home/node/app
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
    depends_on:
      - app
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome
    expose:
      - 4444
    ports:
      - '5901:5900'
<% } _%>
