version: '3.7'

volumes:
  node_modules:

services:
  app:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=dev
    command: 'npm run serve'
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
<% if (hasNightwatch) { _%>

  test:
    build:
      context: .
      target: dev
    environment:
      - LAUNCH_URL=http://app:8080
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    # Add script to wait for app and selinium
    command: 'sleep 5 && npm run test:e2e'
    volumes:
      - ./:/home/node/app
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
    depends_on:
      - app
      - selenium-chrome

  selenium-chrome:
    image: selenium/standalone-chrome
    expose:
      - 4444
    ports:
      - "5901:5900"
<% } _%>
